/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2026-03-06 06:20:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh-CN\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>SmartCoffee</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/element-plus/dist/index.css\" />\n");
      out.write("    <style>\n");
      out.write("      /* 走马灯项基础背景展示 */\n");
      out.write("      .el-carousel__item {\n");
      out.write("        background-size: cover;\n");
      out.write("        background-position: center;\n");
      out.write("        background-repeat: no-repeat;\n");
      out.write("      }\n");
      out.write("      /* 文本居中（与高度 400px 对齐） */\n");
      out.write("      .el-carousel__item h3 {\n");
      out.write("            position: absolute;\n");
      out.write("    top: 12px;\n");
      out.write("    right: 16px;\n");
      out.write("    font-size: 15px;\n");
      out.write("    line-height: 1.2;\n");
      out.write("    margin: 0;\n");
      out.write("    color: #475669;\n");
      out.write("    opacity: 0.9;\n");
      out.write("    text-align: right;\n");
      out.write("      }\n");
      out.write("      /* 为第 1-6 项分别设置背景图（假设为 .jpg） */\n");
      out.write("      .el-carousel__item:nth-child(1) {\n");
      out.write("        background-image: url('");
      out.print( request.getContextPath() );
      out.write("/static/picture/background1.jpg');\n");
      out.write("      }\n");
      out.write("      .el-carousel__item:nth-child(2) {\n");
      out.write("        background-image: url('");
      out.print( request.getContextPath() );
      out.write("/static/picture/background2.jpg');\n");
      out.write("      }\n");
      out.write("      .el-carousel__item:nth-child(3) {\n");
      out.write("        background-image: url('");
      out.print( request.getContextPath() );
      out.write("/static/picture/background3.jpg');\n");
      out.write("      }\n");
      out.write("      .el-carousel__item:nth-child(4) {\n");
      out.write("        background-image: url('");
      out.print( request.getContextPath() );
      out.write("/static/picture/background4.jpg');\n");
      out.write("      }\n");
      out.write("      .el-carousel__item:nth-child(5) {\n");
      out.write("        background-image: url('");
      out.print( request.getContextPath() );
      out.write("/static/picture/background5.jpg');\n");
      out.write("      }\n");
      out.write("      .el-carousel__item:nth-child(6) {\n");
      out.write("        background-image: url('");
      out.print( request.getContextPath() );
      out.write("/static/picture/background6.jpg');\n");
      out.write("      }\n");
      out.write("      .el-row {\n");
      out.write("  margin-bottom: 20px;\n");
      out.write("}\n");
      out.write(".el-row:last-child {\n");
      out.write("  margin-bottom: 0;\n");
      out.write("}\n");
      out.write(".el-col {\n");
      out.write("  border-radius: 4px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".grid-content {\n");
      out.write("  border-radius: 4px;\n");
      out.write("  min-height: 36px;\n");
      out.write("}\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"app\"></div>\n");
      out.write("\n");
      out.write("<script src=\"https://unpkg.com/vue@3/dist/vue.global.js\"></script>\n");
      out.write("<script src=\"https://unpkg.com/element-plus\"></script>\n");
      out.write("<script>\n");
      out.write("  const { createApp, ref } = Vue\n");
      out.write("  const basePath = '");
      out.print( request.getContextPath() );
      out.write("'\n");
      out.write("\n");
      out.write("  const App = {\n");
      out.write("    setup() {\n");
      out.write("      const active = ref(\"1\")\n");
      out.write("      const goINDEX = () => {\n");
      out.write("        window.location.href = basePath + \"/\"\n");
      out.write("      }\n");
      out.write("      const goLogin = () => {\n");
      out.write("        window.location.href = basePath + \"/login\"\n");
      out.write("      }\n");
      out.write("      const goRegister = () => {\n");
      out.write("        window.location.href = basePath + \"/register\"\n");
      out.write("      }\n");
      out.write("      const goWherecoffee =() => {\n");
      out.write("        window.location.href = basePath + \"/wherecoffee\"\n");
      out.write("      }\n");
      out.write("      return { active, basePath, goINDEX,goLogin,goRegister,goWherecoffee }\n");
      out.write("    },\n");
      out.write("    template: `\n");
      out.write("      <div class=\"common-layout\">\n");
      out.write("        <el-container style=\"height: 100vh;\">\n");
      out.write("          <el-header style=\"display:flex; align-items:center; gap:12px; border-bottom: 1px solid #dcdfe6;\">\n");
      out.write("            <span id=\"logo\" style=\"cursor:pointer;\" @click=\"goINDEX\">\n");
      out.write("              <img :src=\"basePath + '/static/picture/logo.jpg'\" alt=\"logo\" style=\"height:40px;\">\n");
      out.write("            </span>\n");
      out.write("            <h2 style=\"margin:0;\">SmartCoffee</h2>\n");
      out.write("            <span style=\"opacity:.7;\">智能咖啡系统</span>\n");
      out.write("          </el-header>\n");
      out.write("          <el-container style=\"overflow: hidden;\">\n");
      out.write("            <el-aside width=\"220px\" style=\"border-right: 1px solid #dcdfe6;\">\n");
      out.write("              <el-menu v-model=\"active\" style=\"border-right: none;\">\n");
      out.write("                <el-menu-item index=\"1\" @click=\"goWherecoffee\">门店</el-menu-item>\n");
      out.write("                <el-menu-item index=\"2\">订单管理</el-menu-item>\n");
      out.write("                <el-sub-menu index=\"3\">\n");
      out.write("                  <template #title>\n");
      out.write("                    <span>用户管理</span>\n");
      out.write("                  </template>\n");
      out.write("                    <el-menu-item index=\"3-1\" @click=\"goLogin\">登录</el-menu-item>\n");
      out.write("                    <el-menu-item index=\"3-2\" @click=\"goRegister\">注册</el-menu-item>\n");
      out.write("                </el-sub-menu>\n");
      out.write("              </el-menu>\n");
      out.write("            </el-aside>\n");
      out.write("                <el-main>\n");
      out.write("                  <p>欢迎使用 SmartCoffee。</p>\n");
      out.write("                  <el-carousel :interval=\"4000\" type=\"card\" height=\"400px\">\n");
      out.write("                <el-carousel-item v-for=\"item in 6\" :key=\"item\">\n");
      out.write("                  <h3 text=\"2xl\" justify=\"center\">广告</h3>\n");
      out.write("                </el-carousel-item>\n");
      out.write("              </el-carousel>\n");
      out.write("              <el-row :gutter=\"20\">\n");
      out.write("                  <el-col :span=\"10\"><div class=\"grid-content ep-bg-purple\" />\n");
      out.write("                  <img :src=\"basePath + '/static/picture/xuanchuan1.jpg'\" alt=\"xuanchuan1\" style=\"height:200px; width:100%; object-fit:cover;\">\n");
      out.write("                    </el-col>\n");
      out.write("                    <el-col :span=\"6\"><div class=\"grid-content ep-bg-purple\" />\n");
      out.write("                  <img :src=\"basePath + '/static/picture/xuanchuan2.jpg'\" alt=\"xuanchuan2\" style=\"height:200px; width:100%; object-fit:cover;\">\n");
      out.write("                    </el-col>\n");
      out.write("                  <el-col :span=\"8\"><div class=\"grid-content ep-bg-purple\" />\n");
      out.write("                    <img :src=\"basePath + '/static/picture/xuanchuan3.jpg'\" alt=\"xuanchuan3\" style=\"height:200px; width:100%; object-fit:cover;\">\n");
      out.write("                    </el-col>\n");
      out.write("              </el-row>\n");
      out.write("              <h1 style=\"text-align:center;\">咖啡豆工艺</h1>\n");
      out.write("              <el-row :gutter=\"20\">\n");
      out.write("                <el-col :span=\"8\"><div class=\"grid-content ep-bg-purple\" /><img :src=\"basePath+'/static/picture/xuanchuan4.jpg'\" alt=\"xuanchuan4\" style=\"height:100%; width:100%; object-fit:cover;\"></el-col>\n");
      out.write("                <el-col :span=\"8\"><div class=\"grid-content ep-bg-purple\" /><img :src=\"basePath+'/static/picture/xuanchuan5.jpg'\" alt=\"xuanchuan5\" style=\"height:100%; width:100%; object-fit:cover;\"></el-col>\n");
      out.write("                <el-col :span=\"8\"><div class=\"grid-content ep-bg-purple\" /><img :src=\"basePath+'/static/picture/xuanchuan6.jpg'\" alt=\"xuanchuan6\" style=\"height:100%; width:100%; object-fit:cover;\"></el-col>\n");
      out.write("             </el-row>\n");
      out.write("              <el-row :gutter=\"20\">\n");
      out.write("                <el-col :span=\"8\"><div class=\"grid-content ep-bg-purple\" /><img :src=\"basePath+'/static/picture/xuanchuan7.jpg'\" alt=\"xuanchuan7\" style=\"height:100%; width:100%; object-fit:cover;\"></el-col>\n");
      out.write("                <el-col :span=\"8\"><div class=\"grid-content ep-bg-purple\" /><img :src=\"basePath+'/static/picture/xuanchuan8.jpg'\" alt=\"xuanchuan8\" style=\"height:100%; width:100%; object-fit:cover;\"></el-col>\n");
      out.write("                <el-col :span=\"8\"><div class=\"grid-content ep-bg-purple\" /><img :src=\"basePath+'/static/picture/xuanchuan9.jpg'\" alt=\"xuanchuan9\" style=\"height:100%; width:100%; object-fit:cover;\"></el-col>\n");
      out.write("              </el-row>\n");
      out.write("               <el-row :gutter=\"20\">\n");
      out.write("                <el-col :span=\"12\"><div class=\"grid-content ep-bg-purple\" /><img :src=\"basePath+'/static/picture/xuanchuan7.jpg'\" alt=\"xuanchuan10\" style=\"height:100%; width:100%; object-fit:cover;\"></el-col>\n");
      out.write("                <el-col :span=\"12\"><div class=\"grid-content ep-bg-purple\" /><img :src=\"basePath+'/static/picture/xuanchuan8.jpg'\" alt=\"xuanchuan11\" style=\"height:100%; width:100%; object-fit:cover;\"></el-col>\n");
      out.write("              </el-row>\n");
      out.write("              <div style=\"margin-top: 24px; padding: 16px 0; border-top: 1px solid #ebeef5; text-align: center; color: #606266; font-size: 12px; line-height: 1.8;\">\n");
      out.write("                <div style=\"font-weight: 600; letter-spacing: 1px; color: #303133;\">ZHINENG·智能企业管理（中国）有限公司</div>\n");
      out.write("                <div>\n");
      out.write("                  <a href=\"https://beian.mps.gov.cn/#/query/webSearch\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"display: inline-flex; align-items: center; color: inherit; text-decoration: none;\">\n");
      out.write("                    <svg width=\"16\" height=\"16\" viewBox=\"0 0 60 60\" aria-hidden=\"true\" focusable=\"false\" style=\"margin-right: 6px;\">\n");
      out.write("                      <path d=\"M32 4c10 8 20 10 28 12v18c0 16-10 24-28 28C14 58 4 50 4 34V16C12 14 22 12 32 4z\" fill=\"#d32f2f\"></path>\n");
      out.write("                      <path d=\"M32 14c6 5 13 6 18 7v13c0 10-6 15-18 18-12-3-18-8-18-18V21c5-1 12-2 18-7z\" fill=\"#ffffff\" opacity=\"0.85\"></path>\n");
      out.write("                      <path d=\"M32 22l4 8 9 1-7 6 2 9-8-5-8 5 2-9-7-6 9-1 4-8z\" fill=\"#d32f2f\"></path>\n");
      out.write("                    </svg>\n");
      out.write("                  </a>\n");
      out.write("                  <span style=\"margin: 0 8px;\">沪公网安备 31010402000253号|沪ICP备17003747号-1</span>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </el-main>\n");
      out.write("          </el-container>\n");
      out.write("        </el-container>\n");
      out.write("      </div>\n");
      out.write("    `\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  const app = createApp(App)\n");
      out.write("  app.use(ElementPlus)\n");
      out.write("  app.mount(\"#app\")\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
