/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2026-03-06 06:22:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class wherecoffee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>SmartCoffee</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/element-plus/dist/index.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/leaflet@1.9.4/dist/leaflet.css\" />\r\n");
      out.write("    <style>\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"app\"></div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://unpkg.com/vue@3/dist/vue.global.js\"></script>\r\n");
      out.write("<script src=\"https://unpkg.com/element-plus\"></script>\r\n");
      out.write("<script src=\"https://unpkg.com/leaflet@1.9.4/dist/leaflet.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  const { createApp, reactive, onMounted } = Vue\r\n");
      out.write("  const basePath = '");
      out.print( request.getContextPath() );
      out.write("'\r\n");
      out.write("\r\n");
      out.write("  const App = {\r\n");
      out.write("    setup() {\r\n");
      out.write("      const goINDEX = () => {\r\n");
      out.write("        window.location.href = basePath + \"/\"\r\n");
      out.write("      }\r\n");
      out.write("      onMounted(() => {\r\n");
      out.write("        const map = L.map('map', {\r\n");
      out.write("          zoomControl: true\r\n");
      out.write("        }).setView([20, 0], 2)\r\n");
      out.write("        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {\r\n");
      out.write("          maxZoom: 19,\r\n");
      out.write("          attribution: '© OpenStreetMap'\r\n");
      out.write("        }).addTo(map)\r\n");
      out.write("      })\r\n");
      out.write("      return {  basePath, goINDEX }\r\n");
      out.write("    },\r\n");
      out.write("    template: `\r\n");
      out.write("      <div class=\"common-layout\">\r\n");
      out.write("        <el-container style=\"height: 100vh;\">\r\n");
      out.write("          <el-header style=\"display:flex; align-items:center; gap:12px; border-bottom: 1px solid #dcdfe6;\">\r\n");
      out.write("            <span id=\"logo\" style=\"cursor:pointer;\" @click=\"goINDEX\">\r\n");
      out.write("              <img :src=\"basePath + '/static/picture/logo.jpg'\" alt=\"logo\" style=\"height:40px;\">\r\n");
      out.write("            </span>\r\n");
      out.write("            <h2 style=\"margin:0;\">SmartCoffee</h2>\r\n");
      out.write("            <span style=\"opacity:.7;\">智能咖啡系统</span>\r\n");
      out.write("          </el-header>\r\n");
      out.write("          <el-container style=\"overflow: hidden;\">\r\n");
      out.write("            <el-aside width=\"220px\" style=\"border-right: 1px solid #dcdfe6;\">\r\n");
      out.write("              <el-menu default-active=\"1\" style=\"border-right: none;\">\r\n");
      out.write("               <el-menu-item index=\"1\">门店</el-menu-item>\r\n");
      out.write("              <h1>欢迎<br>使用<br>智能咖啡系统</h1>\r\n");
      out.write("            </el-aside>\r\n");
      out.write("                <el-main>\r\n");
      out.write("                  <div id=\"map\" style=\"height:600px;width:100%;border:1px solid #ebeef5;border-radius:8px;\"></div>\r\n");
      out.write("            </el-main>\r\n");
      out.write("          </el-container>\r\n");
      out.write("        </el-container>\r\n");
      out.write("      </div>\r\n");
      out.write("    `\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  const app = createApp(App)\r\n");
      out.write("  app.use(ElementPlus)\r\n");
      out.write("  app.mount(\"#app\")\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
